[project]
title = "SageWork's Beastmaster's Ledge"
version = "0.1.0"
port = 8501
slug = "beastmaster-ledge"  
entrypoint = "hello.py"    

[branding]
name = "Beastmaster's Ledge"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#7F4E12"

[data.monsters]
type = "csv"
path = "data/dnd_monsters.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"